### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by SCasarotto** [tradle/react-native-image-store#1]
I am not seeing this package on NPM. https://www.npmjs.com/search?q=react-native-image-store I tried to `yarn add react-native-image-store` but said it was not found. Was it taken down?

**Comment by mvayngrib** [comment]
@SCasarotto no, it was never published to npm. I just did though so give it another try

**Comment by SCasarotto** [comment]
Hey @mvayngrib huge thanks for the fast reply. Hoping this lib will allow me to do iOS and Android offline temporary image storage. Thanks for this!

**Comment by SCasarotto** [comment]
I attempted to follow the instructions in the readme to install and link and neither `react-native link` or the manual setup seems to be working. Both result in the following error when hitting run.

```
/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found
```

Any help here would be appreciated.
