### ISSUE TITLE
iOS Error Building

### ISSUE THREAD

**Issue by SCasarotto** [tradle/react-native-image-store#2]
I have gone through and tried to `react-native link` and Manual setups and both ways results in this error when I build:

```
.../node_modules/react-native/React/Base/RCTBridgeModule.h:10:9: 'React/RCTDefines.h' file not found
```

This project was originally built with Expo and then I ejected to add this library. Any help here would be appreciated.

**Comment by mvayngrib** [comment]
what version of react-native? Have you tried any of the suggestions on StackOverflow, or expo? For example this one: https://forums.expo.io/t/freshly-detached-app-react-rctdefines-h-file-not-found/4291

**Comment by SCasarotto** [comment]
I hadn't looked around in detail because the app builds just fine when I remove "RNImageStore.xcodeproj" from my Libraries Folder. So I figured I would start here. I can attempt to look into other solutions.

**Comment by mvayngrib** [comment]
if your app is open source, i can take a quick look

**Comment by SCasarotto** [comment]
I really appreciate the offer. It's not open source at this time. I also realized I might be able to achieve my same goal within Expo (https://docs.expo.io/versions/latest/sdk/filesystem/) I don't know why I didn't run into this sooner. If this is an option it will allow me not to eject and I will opt for it. For now if you want to close this feel free to and if I come back this route I can reopen this with more questions.

@mvayngrib thanks for being helpful and awesome!

**Comment by mvayngrib** [comment]
ok, good luck!
